### ISSUE TITLE
Could you register NCMB.podspec to CocoaPods Master Repo ?

### ISSUE THREAD

**Issue by sushichop** [NIFCLOUD-mbaas/ncmb_ios#141]
I understand developers can install NCMB(numb_ios) by specifying [git url](https://github.com/NIFTYCloud-mbaas/ncmb_ios.git) in Podfile, but could you have developers be able to install it by versioning as below ?

```Ruby
platform :ios, '10.0'
use_frameworks!

target "YOUR_APP_TARGET" do
    pod 'NCMB', '~> 2.4.0'
end
```

If you do not have a plan to do so(for example, because you do not have enough time to handle it), could I register podspec instead of you ? 
It will be very helpful for many developers(including me😄) if they can install pod by specifying its version.

Thanks in advance.

**Comment by ncmbadmin** [comment]
Thank you for your comment and suggestion. We are so sorry for a late reply.
We will consider on registering NCMB.podspec to CocoaPods Master Repo.
By the way, even NCMB is not registered, you can using the following command to specify tag version to download ncmb_ios.

```
pod 'NCMB', :git => 'https://github.com/NIFCLOUD-mbaas/ncmb_ios.git', :tag => 'v3.0.3'
```

**Comment by ncmbadmin** [comment]
Thank you for making the issue.
Since this case has been answered, it will be closed.
We look forward to your continued support of mobile backend.

**Comment by sushichop** [comment]
@ncmbadmin 
Sorry for my late response. I missed this.

> pod 'NCMB', :git => 'https://github.com/NIFCLOUD-mbaas/ncmb_ios.git', :tag => 'v3.0.3'

Thanks. I have known this DSL from before... and  `:git` syntax does not support dependency in podspec unfortunately . TBH that's why I created the issue...

Do you have any plan to register the pod to the trunk for now, right?😅

Thanks again.
