### ISSUE TITLE
検索したNCMBObjectを変更せずに保存するとinvalid JSONエラー返却されています

### ISSUE THREAD

**Issue by ncmbadmin** [NIFCloud-mbaas/ncmb_ios#148]
SDKの改善にご協力いただきありがとうございます。  
(Thank you for your support our SDK.)

SDKの不具合を報告する場合は、以下の項目を確認してください。  
(If you want to report a bug of the SDK, please confirm the following terms.)

- サンプルコードにAPIキーや個人情報が含まれていないか (The sample code does not include credential information?)
- 同じバグをすでに誰かが報告していてOpenになっているissueはないか (This bug is not being reported?)

## 不具合の概要(Description of bug)

- SDKのバージョン(SDK version)： v.2.4.0
- 不具合が発生した環境(Environment requirement)
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)

```
NCMBQuery *query = [NCMBQuery queryWithClassName:"checkin"];
[query whereKey:"user" equalTo:currentUser];
[query findObjects:&findError];

・・・中略・・・

NSError *saveError = nil;
[checkin save:&saveError];
```

- エラーメッセージ(Error messages): Invalid JSONエラー
- エラー原因の可能性
SDKバージョンが2.4.0でソースでは、取得したNCMBObjectのいずれかのフィールドを変更せずにSaveを実行する場合、サーバーへbodyのdataがnullでリクエストを送信してしまうのでサーバーからInvalid JSONというエラーが返されました。

**Comment by bkzen** [comment]
対応が完了したのでクローズします。
