### ISSUE TITLE
WhereKeyを指定しないと読み込みができません

### ISSUE THREAD

**Issue by atsutko** [NIFCloud-mbaas/ncmb_ios#155]
SDKの改善にご協力いただきありがとうございます。  
(Thank you for your support our SDK.)

SDKの不具合を報告する場合は、以下の項目を確認してください。  
(If you want to report a bug of the SDK, please confirm the following terms.)

- サンプルコードにAPIキーや個人情報が含まれていないか (The sample code does not include credential information?)
- 同じバグをすでに誰かが報告していてOpenになっているissueはないか (This bug is not being reported?)

## 不具合の概要(Description of bug)

- SDKのバージョン(SDK version): v2.4.0
- 不具合が発生した環境(Environment requirement): Xcode9 
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
` let query = NCMBQuery(className: "message")
        query?.findObjectsInBackground({ (objects, error) in
            if error != nil {
                print(error.debugDescription)
            } else {
                print(objects)
            }
        })
    }`
- エラーメッセージ(Error messages)
`"Unauthorized operations for signature." UserInfo={NSLocalizedDescription=Unauthorized operations for signature.})`

findObjectsInBackgroundメソッドの前に、whereKeyExistsのコードを書くことで保存されているデータを読み込むことができるのですが、書かない場合については読み込みができません。
以上、対応のほどよろしくお願いします。

**Comment by truonglongan** [comment]
Hi team
I have tried to connect mBaaS server by this sdk , 
The setting is ok , i can insert new records to class but get data from class is always fail . 
The error is 
 "Unauthorized operations for signature." UserInfo={NSLocalizedDescription=Unauthorized operations for signature.})
by the way , in the same  code in a few days later it worked perfect but not now .
Please  recheck this issues .
Many thanks

**Comment by ncmbsdk** [comment]
リリース完了済みのためクローズいたします
