### ISSUE TITLE
NCMBUser saveInBackground で会員管理(user)の値を更新すると、ユーザー登録時の確認メールが飛んでくる 

### ISSUE THREAD

**Issue by keikosanjo** [NIFCloud-mbaas/ncmb_ios#182]
## 不具合の概要(Description of bug)

- see https://github.com/NIFCloud-mbaas/UserCommunity/issues/902

**Comment by morisatoru** [comment]
不具合解消版を [v3.0.1](https://github.com/NIFCloud-mbaas/ncmb_ios/releases/tag/v3.0.1) にてリリース。
