### ISSUE TITLE
How can I get a role of User when login on iOS ?

### ISSUE THREAD

**Issue by haitacnj** [NIFCloud-mbaas/ncmb_ios#185]
https://github.com/NIFCloud-mbaas/UserCommunity/issues/984

Please helps me on iOS version. Thanks.

**Comment by ncmbadmin** [comment]
Thank you for your question, but we are sorry to say that we do not support about SDK usages here.
So we could not give you the answer for the question.

Please confirm the reply on your community post. Thank you.
