### ISSUE TITLE
UIWebview - Deprecated

### ISSUE THREAD

**Issue by Toshiron** [NIFCLOUD-mbaas/ncmb_ios#196]
つい最近からだと思いますが。アプリをApp Storeにアップロードすると、UIWebViewを使用しているアプリだと以下のようにワーニング出るようになってしまいました。

NCMBRichPushViewクラスにて使用しているようなので、UIWebViewからWKWebViewへの変更をお願いします。

We identified one or more issues with a recent delivery for your app, "xxxx". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs .

**Comment by ncmbadmin** [comment]
issueを投稿いただき、ありがとうございました。
内容を確認させていただき、対応検討を進めていきます。
更新などありましたら、issueにて確認いただければと思います。
