### ISSUE TITLE
iOSで匿名認証するとユーザー情報のセッショントークンが空（nil）になります。

### ISSUE THREAD

**Issue by MonacaSommelierOsaka** [NIFCLOUD-mbaas/ncmb_ios#207]
## 不具合の概要(Description of bug)

- SDKのバージョン(SDK version)
Ver 3.0.3
- 不具合が発生した環境(Environment requirement)
Xode11、iOS13

- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
iOS版のSDK（Ver.3.0.3）で匿名認証後、セッショントークン（SessionToken）がnilに
なってしまいます。
セッショントークンをキーのデータを取りに行くので、無いと困ります。

- 備考
Ver 3.0.0では正常にセッショントークンが取得できます。

**Comment by ncmbadmin** [comment]
お世話になっております、issueをいただき、ありがとうございます。

順次、内容を確認し優先付けをおこなったうえで対応いたしますので、
今しばらくお待ちいただきますようお願いいたします。
対応次第、こちらの issue にて報告いたします。

今後とも、mobile backend どうぞよろしくお願いいたします。
