### ISSUE TITLE
匿名ユーザ関連のテスト追加

### ISSUE THREAD

**Issue by ncmbadmin** [NIFCLOUD-mbaas/ncmb_ios#208]
## 概要

- 以下のテストケースを追加します
  - 匿名ユーザでログインし、currentUserを更新(Save)すると、currentUserも反映するテスト
  - 匿名ユーザでログインし、新規ユーザを作成(SignUp)すると、currentUserは変更されないテスト
  - 匿名ユーザでログインし、currentUserを削除すると、currentUserはnullになるテスト
  - 匿名ユーザでログインし、データストアを更新すると、currentUserは反映されないテスト
  - 匿名ユーザでログインし、データストアを作成すると、currentUserは変更されないテスト
  - 匿名ユーザでログインし、データストアを削除すると、currentUserはnullにならないテスト

**Comment by kobayashi-masaya** [comment]
対応済みであるためcloseします
